version: "3"

networks:
  internal:
    driver: bridge

services:
  nginx:
    image: 'nginx'
    container_name: procontext-nginx
    networks:
      - internal
    ports:
      - '8080:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www/procontext-test
    links:
      - php

  php:
    image: 'php:8.2-fpm'
    container_name: procontext-php
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    volumes:
      - .:/var/www/procontext-test
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: 'mysql'
    container_name: procontext-mysql
    restart: always
    networks:
      - internal
    ports:
      - '3360:3306'
    volumes:
      - ./mysql:/usr/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
